name: 'teams-webhook'
description: 'Send a defined notification to a microsoft teams webhook'
author: 'Freezer00'
inputs:
  webhook_url:
    required: true
    description: 'url of the webhook to use'
  job:
    description: 'JSON parsed job context'
    required: false
  steps:
    description: 'JSON parsed steps context'
    required: false
  needs:
    description: 'JSON parsed needs context'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
