name: 'teams-webhook'
description: 'Send a defined notification to a microsoft teams webhook'
author: 'Freezer00'
inputs:
  webhook_url:
    required: true
    description: 'url of the webhook to use'
  title:
    required: false
    description: 'Card title'
  job:
    description: 'JSON parsed job context'
    required: false
  needs:
    description: 'JSON parsed needs context'
    required: false
  additional_button_title:
    description: 'Display names for optional additional buttons'
    required: false
  additional_button_url:
    description: 'URLs for optional additional buttons'
    required: false
  hide_facts:
    description: 'Flag to keep notification short and not display details about needs'
    default: 'false'
  dry_run:
    description: 'Test action'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: activity
  color: purple
